package com.fis.cdd.core.util;

import java.io.FileInputStream;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 * Obtain the checksum value of a file in hexagonal format
 * The checksum, generated by MD5 algorithm, can be used to
 * check a file's integrity, i.e. whether it has been
 * modified since the last time a checksum was computed
 * Created by Hieu Le on 7/27/15.
 */
public class MD5Checksum {
    private static final String mechanism = "MD5";

    public static String checksum(String pathname) throws IOException {

        MessageDigest md = null;
        try {
            md = MessageDigest.getInstance(mechanism);
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }

        FileInputStream fis = new FileInputStream(pathname);
        byte[] dataBytes = new byte[1024];

        int nRead = 0;

        while ((nRead = fis.read(dataBytes)) != -1) {
            md.update(dataBytes, 0, nRead);
        }
        ;

        byte[] mdbytes = md.digest();

        // Convert the byte to hex format
        StringBuffer sb = new StringBuffer("");
        for (int i = 0; i < mdbytes.length; i++) {
            sb.append(Integer.toString((mdbytes[i] & 0xff) + 0x100, 16).substring(1));
        }

        return sb.toString();
    }

}
